In [2]:
import torch
import torch.nn as nn

In [28]:
with open('../text/faust.txt', 'r') as f:
    text = f.read()

In [29]:
text=text[1016:]

In [30]:
vocab_size=len(list(set(text)))
ch_to_int={ch:i for i,ch in enumerate(list(set(text)))}
int_to_ch={i:ch for i,ch in enumerate(list(set(text)))}
n_embd=512
block_size = 256
encode = lambda x: torch.tensor([ch_to_int[ch] for ch in x])
decode = lambda x: ''.join([int_to_ch[i] for i in x])

In [45]:
token_emb_table=nn.Embedding(vocab_size,n_embd)
        #Step 2:
        # Positional embedding
pos_emb_table=nn.Embedding(block_size,n_embd)

In [46]:
test_enc=encode(text[:block_size])
test_enc

tensor([ 8, 69, 26, 31, 22, 65, 31, 69,  2, 61, 74, 84, 52, 69, 75,  3, 62, 90,
        89, 75, 26, 52, 71, 89, 75, 69, 52,  2, 26, 31, 75,  7, 69,  6, 75, 31,
        62, 90, 21, 69,  2, 75, 67, 65, 52, 71, 66, 75, 11, 69, 73, 69, 52, 11,
        31, 57, 74, 78, 69, 62, 26, 81, 71, 89, 43, 75, 52, 71, 89, 75, 18,  0,
        89, 65, 75, 69, 81, 71, 89, 75,  7, 52, 69, 26,  6, 22, 65, 75,  3, 69,
        26, 31, 75, 73, 81, 75, 89, 22, 65, 31, 69,  2, 37, 74, 58, 90, 89, 65,
        43, 75, 52, 71, 89, 75,  6, 69, 52,  2, 75, 76, 69, 62, 73, 75,  2,  0,
        71, 89, 75, 28, 69,  2, 69,  6, 75, 35, 22, 89,  2, 75, 11, 69,  2, 69,
        52, 11, 31, 37, 74, 82, 89, 62, 75,  7, 62, 59,  2, 11, 31, 75, 69, 81,
        71, 89, 75, 73, 81, 61, 75,  2, 81,  2, 75, 11, 81, 31,  1, 75, 26,  0,
        75,  6, 38, 11, 31, 75, 52, 89, 62, 75, 18, 22, 65, 31, 69,  2,  1, 74,
        35, 52, 69, 75, 52, 89, 62, 75, 22, 81, 26, 75, 84, 81,  2, 26, 31, 75,
        81,  2,  7, 75, 49, 69, 21, 69, 

In [49]:
token_emb_table(test_enc).unsqueeze(0).shape

torch.Size([1, 256, 512])

In [22]:
torch.arange(block_size)

tensor([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
         14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,  27,
         28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,  40,  41,
         42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,  53,  54,  55,
         56,  57,  58,  59,  60,  61,  62,  63,  64,  65,  66,  67,  68,  69,
         70,  71,  72,  73,  74,  75,  76,  77,  78,  79,  80,  81,  82,  83,
         84,  85,  86,  87,  88,  89,  90,  91,  92,  93,  94,  95,  96,  97,
         98,  99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111,
        112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125,
        126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139,
        140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153,
        154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167,
        168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 1

In [42]:
pos_emb_table(torch.arange(0,block_size)).unsqueeze(0).shape

torch.Size([1, 256, 512])

In [50]:
token_emb_table(test_enc).unsqueeze(0)+pos_emb_table(torch.arange(0,block_size)).unsqueeze(0)

tensor([[[ 1.1412,  0.6024,  0.1760,  ..., -1.0118, -2.1957,  0.3013],
         [ 1.4454,  0.2036, -2.6590,  ..., -1.8847,  3.0794, -1.9775],
         [-1.4093, -1.8922,  0.8693,  ..., -0.4578, -1.6912, -2.3335],
         ...,
         [ 0.4069, -0.3821, -1.3589,  ...,  1.3120, -0.8103,  0.5705],
         [ 0.7183, -1.1839, -0.0804,  ..., -1.5940, -1.7581, -1.5368],
         [-1.5956,  1.4077,  0.9379,  ..., -2.9922,  0.7667,  1.5057]]],
       grad_fn=<AddBackward0>)

In [2]:
model1=torch.load("../lightning_logs/version_3/checkpoints/epoch=0-step=217608.ckpt")

In [3]:
context = torch.zeros((1, 1), dtype=torch.long)

In [3]:
import simple_model
GPT=simple_model.GPT
dataset=simple_model.FaustDataset(128)

╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ in <module>:3                                                                                    │
│                                                                                                  │
│   1 import simple_model                                                                          │
│   2 GPT=simple_model.GPT                                                                         │
│ ❱ 3 dataset=simple_model.FaustDataset(128)                                                       │
│   4                                                                                              │
│                                                                                                  │
│ d:\code\SimpleGPT\src\simple_model.py:21 in __init__                                             │
│                                                                                                  │
│    18 │   │   │   import requests                                                                │
│    19 │   │   │   url='https://www.gutenberg.org/files/21000/21000-0.txt'                        │
│    20 │   │   │   r = requests.get(url,timeout=200)                                              │
│ ❱  21 │   │   │   with open(path, 'wb') as f:                                                    │
│    22 │   │   │   │   f.write(r.content)                                                         │
│    23 │   │   │   print('Downloaded text from', url, 'and saved')                                │
│    24                                                                                            │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
FileNotFoundError: [Errno 2] No such file or directory: 'd:\\code\\SimpleGPT\\src\\text/faust.txt'

In [10]:
model = GPT.load_from_checkpoint("../lightning_logs/version_3/checkpoints/epoch=0-step=217608.ckpt")

In [13]:
model.sample(context, 100)

tensor([ 0,  0,  0,  0, 18,  0,  0,  0,  2,  0,  0,  0, 13,  0,  5, 91,  0,  7,
         0,  0,  0,  0,  0,  0,  0,  0, 20, 22,  0,  0,  0,  0,  0,  2,  0,  0,
        47, 64,  0,  0,  0,  0,  0,  0,  2,  0, 64,  0,  0,  0, 57,  0, 66,  1,
         0,  2,  1,  0,  1,  8,  0,  0,  1, 64,  8,  1,  0, 47, 66,  0, 19, 48,
        57,  0, 47, 60,  1, 19, 64,  0,  8,  0,  0, 47, 66, 62,  0, 64,  0,  0,
         0, 21,  1, 34, 62, 11,  1,  0,  1,  0, 40])